name: 🚀 Deploy Laravel to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    name: 📦 SFTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🧬 Checkout latest code
        uses: actions/checkout@v4

      - name: 📤 Deploy to cPanel via SFTP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "."
          target: "/home/tradelab/public_html"
          exclude: |
            .git
            .github
            node_modules
            storage
            vendor
            .env
